### ISSUE TITLE
Giving me an error

### ISSUE THREAD

**Issue by pedrinhoskdaniel** [Isigar/relisoft_core#3]
@relisoftcore/core/log.lua:4: attempt to index a nil value (local 'xPlayer')

HELP PLEASE

**Comment by Isigar** [comment]
Which way are you using log function? Somewhere in your script?

**Comment by pedrinhoskdaniel** [comment]
I don't know i downloaded and dragged into the resources folder and did all the steps that were said necessary

**Comment by Isigar** [comment]
Very odd, do you rename folder to 'rcore' ?

**Comment by pedrinhoskdaniel** [comment]
no i didn't

**Comment by Isigar** [comment]
So do it please, i will add it into readme. Rename resource to rcore
